#!/bin/bash

CODE=scuff-static

for N in 1948 7856
do

  ##################################################
  # first run to get capacitance matrix 
  ##################################################
  ARGS=""
  ARGS="${ARGS} --geometry StriplineCapacitor_${N}.scuffgeo"
  ARGS="${ARGS} --CapFile  StriplineCapacitor_${N}.CapMatrix"

  ${CODE} ${ARGS}

  ##################################################
  # second run to get field visualization data
  ##################################################
  ARGS=""
  ARGS="${ARGS} --geometry StriplineCapacitor_${N}.scuffgeo"
  ARGS="${ARGS} --PotentialFile MyPotentialFile"
  ARGS="${ARGS} --FVMesh FVMesh.msh"

  ${CODE} ${ARGS}

done
