#!/bin/bash

#
# this script should be executed from within the 
# scuff-em/doc/site directory
#

if [ "${PWD##*/}" != "site" ]
then
  echo "whoops! you are executing this script from the wrong directory"
  exit
fi

git add --all .
git commit -a -m"updates"
git push origin gh-pages
