#!/bin/bash

if [ $# -ne 3 ]
then
  echo "usage example: Filter M 2 -1"
  exit
fi

TYPE=$1
LV=$2
MV=$3

AWKSCRIPT="\$5==\"${TYPE}\" && \$6==${LV} && \$7==${MV} {print}"

echo AWKSCRIPT is ${AWKSCRIPT}

for N in 327 654 1362
do
  awk "${AWKSCRIPT}" E10Sphere_${N}.TMatrix | sort -g -k2 -k4 -k3 > N${N}_${TYPE}${LV}${MV}
done
