#!/bin/bash

GEOLIST="E10E10_762 E1P1E1P1_762 E1P1E1P2_762 Sphere_E2E20_762"
GEOLIST="${GEOLIST} E10E10_3348 E1P1E1P1_3348 E1P1E1P2_3348 Sphere_E2E20_3348"

for G in ${GEOLIST}
do
  ARGS="--geometry Sphere_${G}.scuffgeo"
  ARGS="${ARGS} --OmegaFile OmegaFile" 
  ARGS="${ARGS} --lMax 3"
  ARGS="${ARGS} --cache MyCache.scuffcache"
  ARGS="${ARGS} --ExcludeLineCharges"

  ../GetTMatrix ${ARGS}
done

for G in ${GEOLIST}
do
  ARGS="--geometry Sphere_${G}.scuffgeo"
  ARGS="${ARGS} --OmegaFile OmegaFile" 
  ARGS="${ARGS} --lMax 3"
  ARGS="${ARGS} --cache MyCache.scuffcache"
  ARGS="${ARGS} --ExcludeHalfBFs

  ../GetTMatrix ${ARGS}
done

for G in ${GEOLIST}
do
  ARGS="--geometry Sphere_${G}.scuffgeo"
  ARGS="${ARGS} --OmegaFile OmegaFile" 
  ARGS="${ARGS} --lMax 3"
  ARGS="${ARGS} --cache MyCache.scuffcache"
  ARGS="${ARGS}

  ../GetTMatrix ${ARGS}
done
