#!/bin/bash

if [ $# -eq 6 ] 
then
 TYPE=$1
 LV=$2
 MV=$3
 TYPEP=$4
 LVP=$5
 MVP=$6
 EXT=${TYPE}${LV}${MV}_${TYPEP}${LVP}${MVP}
elif [ $# -eq 3 ]
then
 TYPE=$1
 LV=$2
 MV=$3
 TYPEP=$1
 LVP=$2
 MVP=$3
 EXT=${TYPE}${LV}${MV}
else
  echo "usage example: Filter M 2 -1 [ E 1 3 ]"
  exit
fi

AWKSCRIPT="\$5==\"${TYPE}\" && \$6==${LV} && \$7==${MV} && \$2==\"${TYPEP}\" && \$3==${LVP} && \$4==${MVP} {printf(\" %e %e %e \\n\", \$1, \$8, \$9)}"

awk "${AWKSCRIPT}"
